# Generated by Django 5.2.17 on 2026-09-26 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(db_index=True, max_length=64)),
                ("endpoint", models.CharField(max_length=255)),
                ("success", models.BooleanField(default=False)),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("data_type", models.CharField(max_length=120)),
                ("update_frequency", models.CharField(blank=True, max_length=80)),
                ("coverage", models.CharField(blank=True, max_length=120)),
                ("attribution", models.TextField(blank=True)),
                ("homepage_url", models.URLField(blank=True)),
                ("docs_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("requires_key", "Requires API key"),
                            ("unavailable", "Unavailable"),
                            ("planned", "Planned integration"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=120)),
                ("state", models.CharField(blank=True, db_index=True, max_length=120)),
                ("district", models.CharField(blank=True, max_length=120)),
                (
                    "country_code",
                    models.CharField(db_index=True, default="IN", max_length=2),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=64)),
                ("population", models.PositiveIntegerField(blank=True, null=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                (
                    "external_geoname_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["name", "state"], name="weather_loc_name_0b4632_idx"
                    ),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="weather_loc_latitud_1f8130_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "state", "country_code"),
                        name="uniq_location_name_state_country",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WeatherAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hazard_type", models.CharField(db_index=True, max_length=64)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("extreme", "Extreme"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("derived", "Model-derived estimate"),
                            ("official", "Official authority"),
                            ("observed", "Observed condition"),
                        ],
                        default="derived",
                        max_length=20,
                    ),
                ),
                ("area_name", models.CharField(blank=True, max_length=200)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("source_name", models.CharField(blank=True, max_length=120)),
                ("recommended_action", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="weather.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-severity", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="WeatherForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period",
                    models.CharField(
                        choices=[("hourly", "Hourly"), ("daily", "Daily")],
                        max_length=10,
                    ),
                ),
                ("forecast_time", models.DateTimeField(db_index=True)),
                ("temperature_c", models.FloatField(blank=True, null=True)),
                ("temperature_min_c", models.FloatField(blank=True, null=True)),
                ("temperature_max_c", models.FloatField(blank=True, null=True)),
                ("humidity_pct", models.FloatField(blank=True, null=True)),
                ("precipitation_mm", models.FloatField(blank=True, null=True)),
                (
                    "precipitation_probability_pct",
                    models.FloatField(blank=True, null=True),
                ),
                ("wind_speed_kmh", models.FloatField(blank=True, null=True)),
                (
                    "weather_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("weather_description", models.CharField(blank=True, max_length=120)),
                ("thunderstorm_hint", models.BooleanField(default=False)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="weather.location",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="weather.datasource",
                    ),
                ),
            ],
            options={
                "ordering": ["forecast_time"],
                "indexes": [
                    models.Index(
                        fields=["location", "period", "forecast_time"],
                        name="weather_wea_locatio_f596e9_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("location", "period", "forecast_time"),
                        name="uniq_forecast_location_period_time",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WeatherObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("observed_at", models.DateTimeField(db_index=True)),
                (
                    "data_kind",
                    models.CharField(
                        choices=[
                            ("live", "Live observation"),
                            ("forecast", "Forecast"),
                            ("model", "Model-derived"),
                            ("cached", "Cached"),
                        ],
                        default="live",
                        max_length=20,
                    ),
                ),
                ("temperature_c", models.FloatField(blank=True, null=True)),
                ("feels_like_c", models.FloatField(blank=True, null=True)),
                ("humidity_pct", models.FloatField(blank=True, null=True)),
                ("pressure_hpa", models.FloatField(blank=True, null=True)),
                ("wind_speed_kmh", models.FloatField(blank=True, null=True)),
                ("wind_direction_deg", models.FloatField(blank=True, null=True)),
                ("visibility_km", models.FloatField(blank=True, null=True)),
                ("cloud_cover_pct", models.FloatField(blank=True, null=True)),
                ("rainfall_mm", models.FloatField(blank=True, null=True)),
                ("uv_index", models.FloatField(blank=True, null=True)),
                (
                    "weather_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("weather_description", models.CharField(blank=True, max_length=120)),
                ("cape_jkg", models.FloatField(blank=True, null=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="weather.location",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="weather.datasource",
                    ),
                ),
            ],
            options={
                "ordering": ["-observed_at"],
                "indexes": [
                    models.Index(
                        fields=["location", "-observed_at"],
                        name="weather_wea_locatio_052e45_idx",
                    )
                ],
            },
        ),
    ]
