# Generated by Django 5.2.17 on 2026-09-27 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertDispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(db_index=True, max_length=32)),
                ("location_label", models.CharField(blank=True, max_length=160)),
                ("severity", models.CharField(max_length=20)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("fingerprint", models.CharField(max_length=64, unique=True)),
                (
                    "last_sent_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("send_count", models.PositiveIntegerField(default=0)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alert_dispatches",
                        to="weather.location",
                    ),
                ),
            ],
            options={
                "ordering": ("-last_sent_at",),
            },
        ),
        migrations.CreateModel(
            name="SMSSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("mobile_number", models.CharField(max_length=16)),
                (
                    "normalized_mobile_number",
                    models.CharField(max_length=16, unique=True),
                ),
                ("location_label", models.CharField(max_length=160)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("hi", "Hindi"), ("mr", "Marathi")],
                        default="en",
                        max_length=8,
                    ),
                ),
                ("alert_preferences", models.JSONField(default=list)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("phone_verified", models.BooleanField(default=False)),
                ("consent_given", models.BooleanField(default=False)),
                ("consent_timestamp", models.DateTimeField(blank=True, null=True)),
                ("last_alert_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_subscribers",
                        to="weather.location",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SMSDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("masked_recipient", models.CharField(max_length=20)),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                ("category", models.CharField(max_length=32)),
                ("language", models.CharField(default="en", max_length=8)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                            ("DEMO", "Demo"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("provider", models.CharField(default="demo", max_length=32)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "subscriber",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to="weather.smssubscriber",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="smssubscriber",
            index=models.Index(
                fields=["is_active", "language"], name="weather_sms_is_acti_eeb9fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smssubscriber",
            index=models.Index(
                fields=["location", "is_active"], name="weather_sms_locatio_766140_idx"
            ),
        ),
    ]
